# Select Mac OSX
os: osx

# We require sudo support, so we can not use the new Travis Docker based building system
sudo: required

# Only track the master branch. Every push to the master creates a new version (according to Git Flow)
branches:
  only:
    - master

# Before running any scripts set the rights of the file to execute. Otherwise Travis will fail with "permission denied"
before_install:
- chmod +x ./ci/install-unity.sh
- chmod +x ./ci/build.sh

# Install Unity
install:
- ./ci/install-unity.sh

# Execute the build script
script:
- ./ci/build.sh
